#!/usr/bin/env python3
"""
MoE Rebrand Script
--------------------
One-time script: strips "Cyber Forge" branding out of this repo and
replaces it with MoE, renames the puller script, and fixes the stale
'cyberforge_assets' folder references so they correctly point at 'assets'.

Run this from inside your repo folder:
    python rebrand.py

Works identically on Windows PowerShell, Git Bash, Mac Terminal, Linux --
no sed, no shell-specific syntax, just plain Python.
"""

import os
import re

REPLACEMENTS = [
    (r"Cyber Forge Asset Puller v3", "MoE Sim Asset Puller"),
    (r"Cyber Forge Asset Manifest Generator", "MoE Asset Manifest Generator"),
    (r"Cyber Forge open-asset repository", "MoE open-asset repository"),
    (r"license-cleared background and icon assets for Cyber Forge",
     "license-cleared background and icon assets for Ministry of Education (MoE)"),
    (r"cyberforge_asset_puller\.py", "asset_puller.py"),
    (r"cyberforge_assets/", "assets/"),
    (r'OUTPUT_ROOT = "cyberforge_assets"', 'OUTPUT_ROOT = "assets"'),
    (r'ASSET_ROOT = "cyberforge_assets"', 'ASSET_ROOT = "assets"'),
    (r"Auto-generated by cyberforge_asset_puller\.py", "Auto-generated by asset_puller.py"),
]

FILES_TO_EDIT = [
    "asset_puller.py",           # may not exist yet if not renamed
    "cyberforge_asset_puller.py",  # old name, in case rename hasn't happened
    "generate_asset_manifest.py",
    "README.md",
    os.path.join("assets", "SOURCES.md"),
]


def rename_script():
    old_name = "cyberforge_asset_puller.py"
    new_name = "asset_puller.py"
    if os.path.exists(old_name) and not os.path.exists(new_name):
        os.rename(old_name, new_name)
        print(f"Renamed: {old_name} -> {new_name}")
    elif os.path.exists(new_name):
        print(f"Already renamed: {new_name} exists")
    else:
        print(f"Note: {old_name} not found, skipping rename")


def apply_replacements(path):
    if not os.path.exists(path):
        return False

    with open(path, "r", encoding="utf-8") as f:
        content = f.read()

    original = content
    for pattern, replacement in REPLACEMENTS:
        content = re.sub(pattern, replacement, content)

    if content != original:
        with open(path, "w", encoding="utf-8") as f:
            f.write(content)
        print(f"Updated: {path}")
        return True
    else:
        print(f"No changes needed: {path}")
        return False


def check_remaining(paths):
    print("\n--- Checking for any leftover 'cyber' mentions ---")
    found_any = False
    for path in paths:
        if not os.path.exists(path):
            continue
        with open(path, "r", encoding="utf-8") as f:
            for i, line in enumerate(f, 1):
                if "cyber" in line.lower():
                    print(f"  {path}:{i}: {line.strip()}")
                    found_any = True
    if not found_any:
        print("  Clean -- no 'cyber' mentions left.")


def main():
    rename_script()

    for path in FILES_TO_EDIT:
        apply_replacements(path)

    check_remaining(FILES_TO_EDIT)

    print("\nDone. Now run:")
    print("  git add -A")
    print('  git commit -m "Remove Cyber Forge branding, rebrand for MoE use"')
    print("  git push")


if __name__ == "__main__":
    main()
